[package]
name = "singerprint"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5"
rustfft = "6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.4", features = ["derive"] }